demo/config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'
  
  root 'say#hello'
 

end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
    @files = Dir.glob('*')
  end
end
  

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/say_helper.rb
module SayHelper
end

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

demo/app/views/say/goodbye.html.erb
<h1>Good bye </h1>
<p>
	Rails is simple
</p>
<p>
Say 
<%= link_to "hello", say_hello_path%>!
Addition: <%= 1+2 %> </p>
<p>Concatenation: <%= "cow" + "boy" %></p>
<p>	<% for file in @files %>
file name is: <%= file %></p>

<% end %>

demo/app/views/say/hello.html.erb
<h1>Hello Rails</h1>
<p>
	It is now <%= @time%>
	</p>
	<p>
Time to say
<%= link_to "Goodbye", say_goodbye_path %>!
Time in one hour: <%= 1.hour.from_now %>
</p>







<p>Name</p>
<%= text_field(:person, :name) %>